### ISSUE TITLE
Issue : Bad plugin hooks that failed to load

### ISSUE THREAD

**Issue by bahinapster** [tidev/ti.es6#1]
`INFO]  Found Titanium plugin id=ti.es6 version=1.3.0 
[WARN]  Bad plugin hooks that failed to load:
[WARN]  __PATH__TO_PROJECT__/plugins/ti.es6/1.3.0/hooks/ti.es6.js
[WARN]    Error: Cannot find module 'klaw-sync'
[WARN]        at Function.Module._resolveFilename (module.js:536:15)
[WARN]        at Function.Module._load (module.js:466:25)
[WARN]        at Module.require (module.js:579:17)
[WARN]        at require (internal/module.js:11:18)
[WARN]        at Object.<anonymous> (__PATH__TO_PROJECT__/plugins/ti.es6/1.3.0/hooks/ti.es6.js:10:11)
[WARN]        at Module._compile (module.js:635:30)
[WARN]        at Object.Module._extensions..js (module.js:646:10)
[WARN]        at Module.load (module.js:554:32)
[WARN]        at tryModuleLoad (module.js:497:12)
[WARN]        at Function.Module._load (module.js:489:3)
[WARN]    ---------------------------------------------
[WARN]        at Object.exports.execFile (child_process.js:356:9)
[WARN]        at exports.exec (child_process.js:142:18)
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/lib/environ.js:267:3
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:3824:9
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:460:16
[WARN]        at replenish (__PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:977:25)
[WARN]        at iterateeCallback (__PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:967:17)
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:944:16
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:3821:13
[WARN]    ---------------------------------------------
[WARN]        at Object.exports.execFile (child_process.js:356:9)
[WARN]        at exports.exec (child_process.js:142:18)
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/lib/environ.js:227:6
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:3816:26
[WARN]        at replenish (__PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:982:17)
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:986:9
[WARN]        at eachOfLimit (__PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:1011:22)
[WARN]        at __PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:1016:16
[WARN]        at _parallel (__PATH__/.appcelerator/install/7.0.9/package/node_modules/titanium/node_modules/node-appc/node_modules/async/dist/async.js:3815:5)`

Plugin : 1.3.0
CLI : 7.0.9
SDK : 7.5.0
Plaftorm : iOS

**Comment by ewanharris** [comment]
Hey @bahinapster, did you run `npm install --production` inside the plugin directory (__PATH__TO_PROJECT__/plugins/ti.es6/1.3.0) after copying the file contents across?

**Comment by bahinapster** [comment]
Hello @ewanharris 
now it works after running the command, thank you 👍

**Comment by bahinapster** [comment]
Hello again,
now i got this 

(node:62120) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'PATH/app.js'
(node:62120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
